language: emacs-lisp
before_install:
  - sudo sh test/provision.sh
install:
  - cask install
env:
  - EMACS=emacs23
  - EMACS=emacs24
  - EMACS=emacs-snapshot
script:
  - make compile
  - make test
matrix:
  allow_failures:
    - env: EMACS=emacs23
